language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-stable
  - Pharo-6.0
  
# Disable emails
notifications:
email: false
