SystemOrganization addCategory: #PathVis!
SystemOrganization addCategory: 'PathVis-Algorithms'!
SystemOrganization addCategory: 'PathVis-Generators'!
SystemOrganization addCategory: 'PathVis-Graph'!
SystemOrganization addCategory: 'PathVis-Grid'!
SystemOrganization addCategory: 'PathVis-Notificators'!
SystemOrganization addCategory: 'PathVis-Renderers'!
SystemOrganization addCategory: 'PathVis-Spaces'!
